Reuse single grpc connection
EmerisHQ/demeris-api-server pull request #115
Opened 2022-04-19 07:38 UTC by akhilkumarpilli

Fixes: #108

2022-04-19 08:18 UTC, 0xbala-k approved these changes

2022-04-19 16:22 UTC, pitasi requested changes
This PR is similar to what I had in mind but I wouldn't use the gin.Context since the client it's instantiated once and doesn't really change between requests (e.g. logger is specific for each request so it's okay to have it in the context).

I'd wait for me to merge my two currently open PRs:
- https://github.com/EmerisHQ/demeris-api-server/pull/113
- https://github.com/EmerisHQ/demeris-api-server/pull/114
and then you will be able to pass your gRPC connections map as a param of the handlers closures.

2022-04-20 05:26 UTC, akhilkumarpilli commented
> This PR is similar to what I had in mind but I wouldn't use the gin.Context since the client it's instantiated once and doesn't really change between requests (e.g. logger is specific for each request so it's okay to have it in the context).

Sure, will update.

2022-04-20 05:36 UTC, DeshErBojhaa approved these changes
LGTM! 🎊 🎉

2022-04-20 07:46 UTC, pitasi requested changes

2022-04-20 07:46 UTC, pitasi commented on sdkservice/sdkservice.go
> +func (clients SDKServiceClients) GetSDKServiceClient(chainName, version string) (sdkutilities.Client, *apierrors.Error) {
do we really need to pass chainName? I think sdk-services is not specific to a particular chain

```suggestion
func (clients SDKServiceClients) GetSDKServiceClient(version string) (sdkutilities.Client, *apierrors.Error) {
```

2022-04-20 07:46 UTC, pitasi commented on sdkservice/sdkservice.go
> +	}
let's use apierrors from handlers only, so this code can be re-used in other parts of the codebase if we want to

```suggestion
	if !ok {
		return client, fmt.Errorf("cannot retrieve sdk-service client for version %s", version)
	}
```

2022-04-20 07:52 UTC, akhilkumarpilli commented on sdkservice/sdkservice.go
> +func (clients SDKServiceClients) GetSDKServiceClient(chainName, version string) (sdkutilities.Client, *apierrors.Error) {
Used chainname here for errors so that I thought it will be easy for debugging.

2022-04-20 07:54 UTC, akhilkumarpilli commented on sdkservice/sdkservice.go
> +	}
Instead of writing same apierrors.New code in lot of places, I thought we can have it here only once. And also we can get only error text using e.InternalCause. Hope it will not be any problem. WDYT?

2022-04-20 07:56 UTC, akhilkumarpilli commented on sdkservice/sdkservice.go
> +func (clients SDKServiceClients) GetSDKServiceClient(chainName, version string) (sdkutilities.Client, *apierrors.Error) {
And it will also be helpful to have chainname as we are getting version from specific chain details.

2022-04-20 08:10 UTC, pitasi commented on sdkservice/sdkservice.go
> +func (clients SDKServiceClients) GetSDKServiceClient(chainName, version string) (sdkutilities.Client, *apierrors.Error) {
the chain_name will be automatically included in the logging context (along with all the parameters of the http request)

2022-04-20 08:19 UTC, pitasi commented on sdkservice/sdkservice.go
> +	}
uhm ok let's leave it here, we can just remove these lines since they don't add anything:
```
.WithLogContext(
			fmt.Errorf("cannot retrieve chain's sdk-service for version %s", version),
			"name",
			chainName,
		)
```

2022-04-20 08:51 UTC, pitasi approved these changes

2022-04-20 08:56 UTC, merged