feat: add aggregated /chains/status endpoint
EmerisHQ/demeris-api-server pull request #117
Opened 2022-04-21 14:17 UTC by pitasi

This PR adds `/chains/status` which aggregates all the `/chain/XXX/status` calls into one.

The list of the returned chains only contains **enabled** chains. This information can be used by the frontend to establish whether a chain is enabled or not.

Close #715.

2022-04-21 15:20 UTC, DeshErBojhaa requested changes

2022-04-21 15:20 UTC, DeshErBojhaa commented on api/chains/chains.go
> +// @Failure 500,403 {object} apierrors.UserFacingError
Do we return 403?

2022-04-21 15:20 UTC, DeshErBojhaa commented on api/chains/models.go
> +}
```suggestion
func NewChainsStatusesResponse(sz int) ChainsStatusesResponse {
	return ChainsStatusesResponse{
		Chains: make(map[string]ChainStatus, 0, sz),
	}
}
```
then on `GetChainsStatuses`  

```go
res := NewChainsStatusesResponse(len(status))
```

2022-04-21 15:47 UTC, pitasi commented on api/chains/chains.go
> +// @Failure 500,403 {object} apierrors.UserFacingError
nope!, removed

2022-04-21 15:48 UTC, pitasi commented on api/chains/models.go
> +}
It's a map so I omitted the "0" but added a size!

2022-04-21 16:15 UTC, DeshErBojhaa commented on api/chains/models.go
> +}
opps my bad :p

2022-04-21 16:16 UTC, DeshErBojhaa approved these changes
🎊

2022-04-22 08:57 UTC, akhilkumarpilli approved these changes

2022-04-22 08:58 UTC, merged