enhance /chains endpoint
EmerisHQ/demeris-api-server pull request #118
Opened 2022-04-22 08:57 UTC by akhilkumarpilli

Fixes part of https://github.com/EmerisHQ/demeris-backend/issues/718

2022-04-22 09:44 UTC, DeshErBojhaa requested changes
Wonderful 🎊 
One minor update req.

2022-04-22 09:44 UTC, DeshErBojhaa commented on api/database/chains.go
> +type ChainWithStatus struct {
Please add `omitempty` json tag. Main reason for this api endpoint is to reduce FE #of polling, **also** reducing the payload size.

2022-04-22 10:37 UTC, pitasi approved these changes
lgtm!

2022-04-22 12:16 UTC, DeshErBojhaa approved these changes

2022-04-22 21:04 UTC, tbruyelle requested changes
Thanks for this change, this will drastically reduce the number of calls from the front!

Note: we should have unit tests in `api/database` !!

2022-04-22 21:04 UTC, tbruyelle commented on api/database/chains.go
> +type ChainWithStatus struct {
`omitempty` on types like `bool` will remove the field from the JSON if the field value is false, is it really what we want ?

This can typically produce Javascript error when the front will try to read `chain.enabled` (because the field is absent).

2022-04-22 21:04 UTC, tbruyelle commented on api/database/chains.go
> +		c.*,
`SELECT *` should be avoided since it can trigger error during the scanning of the rows into the struct. For instance when a column is added to the table and the struct doesn't reflect that yet.

2022-04-22 21:04 UTC, tbruyelle commented on api/chains/chains.go
>  			return
Errors coming from database should more likely be returned as a `500 internal server error` rather than a `400 bad request`.

(sorry, it's not part of your change but it stung me to the core ^^)

2022-04-22 21:48 UTC, tbruyelle commented
I was wondering if there's not conflict with this change here ? https://github.com/EmerisHQ/demeris-api-server/pull/117

2022-04-25 04:26 UTC, akhilkumarpilli commented
> Thanks for this change, this will drastically reduce the number of calls from the front!
> 
> Note: we should have unit tests in `api/database` !!

Sure, will create a separate issue and add unit tests for database in other PR.

2022-04-25 04:27 UTC, akhilkumarpilli commented
> I was wondering if there's not conflict with this change here ? #117

I think we don't have any conflicts. We will have #117 as separate endpoint.

2022-04-25 05:57 UTC, akhilkumarpilli commented on api/database/chains.go
> +type ChainWithStatus struct {
Yeah, will remove `omitempty` on bool values and also will follow same as cns.Chain struct.

2022-04-25 08:46 UTC, tbruyelle commented on api/database/chains.go
> +type ChainWithStatus struct {
Note this doesn't affect only `bool` but also some other types that have a *default* value, like `string`, slices and all kind of numbers.

2022-04-25 08:49 UTC, tbruyelle commented
> I think we don't have any conflicts. We will have #117 as separate endpoint.

Sorry I didn't mean conflict in term of code, but in term of issue. I fear they both relate to the same issue https://github.com/EmerisHQ/demeris-backend/issues/718. 

@Pitasi Can you tell us which issue you're tackling with #117 ?

2022-04-25 09:21 UTC, akhilkumarpilli commented on api/database/chains.go
> +type ChainWithStatus struct {
Yes, I removed omitempty from all other fields too. Just `public_ node_endpoints` and `cosmos_sdk_version` fields have `omitempty` tag as we follow same in [cns.Chain](https://github.com/EmerisHQ/demeris-backend-models/blob/main/cns/cns.go#L31-L32) struct

2022-04-25 09:40 UTC, tbruyelle commented on api/database/chains.go
> +type ChainWithStatus struct {
Nice!!

Just to finish, `omitempty` on struct value like `PublicNodeEnpoints` will have no effect, the struct will always be serialized into JSON (proof https://go.dev/play/p/WOjsMblArVb). To have the expected behavior, you have to use a struct pointer instead.

2022-04-26 08:29 UTC, pitasi commented
@tbruyelle https://github.com/emerishq/demeris-backend/issues/715

rationale: we thought of starting out with `/status` which was pretty simple to make, then adding `/chains` which required a little more effort (but Akhil did pretty fast tbh 😁)

2022-04-26 08:58 UTC, tbruyelle approved these changes
Nice job!

2022-04-26 10:46 UTC, merged