add api/database unit tests
EmerisHQ/demeris-api-server pull request #121
Opened 2022-04-27 15:37 UTC by akhilkumarpilli

Fixes: #120

2022-04-28 09:28 UTC, akhilkumarpilli commented
Modified these methods as there are some issues when calling them. Faced errors like `expected slice but got struct`, `Scan error on column index 8, name "hops": unsupported Scan, storing driver.Value type []uint8 into type *[]string`. And one strange thing is that we are not using these methods anywhere in api-server.Will we have any problem with these changes? @EmerisHQ/emeris-backend 

https://github.com/EmerisHQ/demeris-api-server/pull/121/files#diff-195d48f416d07d45a67a80648e239833c662ce2fc7e8b8081926befedb0e7aacR11-R65

https://github.com/EmerisHQ/demeris-api-server/pull/121/files#diff-242a7beb64f01954fdd9ac78ef3e50e349eed4cb1db69146f85cd29f5b3c3a2dR10-R31

Thank you.

2022-04-28 12:25 UTC, tbruyelle commented
> Modified these methods as there are some issues when calling them. Faced errors like `expected slice but got struct`, `Scan error on column index 8, name "hops": unsupported Scan, storing driver.Value type []uint8 into type *[]string`. And one strange thing is that we are not using these methods anywhere in api-server.Will we have any problem with these changes? @EmerisHQ/emeris-backend
> 
> https://github.com/EmerisHQ/demeris-api-server/pull/121/files#diff-195d48f416d07d45a67a80648e239833c662ce2fc7e8b8081926befedb0e7aacR11-R65
> 
> https://github.com/EmerisHQ/demeris-api-server/pull/121/files#diff-242a7beb64f01954fdd9ac78ef3e50e349eed4cb1db69146f85cd29f5b3c3a2dR10-R31
> 
> Thank you.

I would say if the signature of the method specifies it returns a single result, the correct fix is to replace `sqlx.Select` by `sqlx.Get` and keep a struct instead of a slice for the `dest` parameter. And the test should assert the underlying sql always returns a single row.

2022-04-28 13:18 UTC, tbruyelle requested changes
Thanks for all these good tests!! 

We need to conclude our conversation about `Select` vs `Get` and I'll approve the PR.

2022-04-28 13:18 UTC, tbruyelle commented on api/database/chains_test.go
> +	require.Equal(t, expBytes, actualBytes)
`JSONEq` gives a far more readable output in case of diff : 

```suggestion
	require.JSONEq(t, string(expBytes), string(actualBytes))
```

Example where I intentionally introduced a change on the `Logo` field :
![image](https://user-images.githubusercontent.com/92280/165758040-d3424a59-b47b-432e-98e2-93b72b9ca72a.png)

Compared to the output of `Equal` with bytes:
![image](https://user-images.githubusercontent.com/92280/165760183-624c5d44-d7a2-40a2-8c2c-e91bc3de1c69.png)

2022-04-29 04:38 UTC, akhilkumarpilli commented
> I would say if the signature of the method specifies it returns a single result, the correct fix is to replace sqlx.Select by sqlx.Get and keep a struct instead of a slice for the dest parameter. And the test should assert the underlying sql always returns a single row.

Sure, updated.

2022-04-29 08:22 UTC, pitasi commented on api/database/chains_test.go
> +}
sorry I don't understand why we do this instead of just `require.Equal(t, expected, actual)`

2022-04-29 08:37 UTC, akhilkumarpilli commented on api/database/chains_test.go
> +}
We will get ID field from db and we cannot compare it as it will be dynamic. So, I just marshaling it to json so that ID field will be ignored.

2022-04-29 08:41 UTC, pitasi commented on api/database/chains_test.go
> +}
Makes sense, it's probably worth adding a comment explaining it 😄

2022-04-29 08:58 UTC, pitasi approved these changes

2022-04-29 09:00 UTC, tbruyelle commented on api/database/chains_test.go
> +}
Ideally, I think a struct that has been inserted in the database should have its ID updated from 0 to the correct value. This is possible thanks to the `RETURNING` sql statement.
For instance, you call `INSERT INTO table (name) values ("foo") RETURNING ID`, then when you execute the query you can read the ID just like if you executed a `SELECT`.

WDYT (not for now ofc) ?

This has the benefit of having a complete struct after the call to `db.InsertTable`, so if you return the struct to the client he gets the new ID, and then for the tests you can call `require.Equal` directly on it.

2022-04-29 09:03 UTC, tbruyelle approved these changes

2022-04-29 09:03 UTC, pitasi commented on api/database/chains_test.go
> +}
yes it's something we can do, can you open a ticket in the backlog for this? 😁

2022-04-29 09:19 UTC, merged