Add Crescent APR calculation to api-server
EmerisHQ/demeris-api-server pull request #123
Opened 2022-05-02 09:37 UTC by 0xbala-k

Crescent implements its own mint module and the apr is calculated as follows
apr=(1-budget rate)*(1-tax)*CurrentInflationAmount/Bonded tokens

2022-05-02 12:13 UTC, sgerogia requested changes

2022-05-02 12:13 UTC, sgerogia commented on api/chains/chains.go
> +		if budget.Name == "budget-ecosystem-incentive" || budget.Name == "budget-dev-team" {
Extract as constants?

2022-05-02 12:13 UTC, sgerogia commented on api/chains/chains.go
> +func getCrescentAPR(c *gin.Context, chain cns.Chain, bondedTokens sdktypes.Dec, client sdkutilities.Client) (string, error) {
Can the method be broken up into data fetching and calculation?
This way you can mock fetched data add a unit test on the calculation logic (e.g. edge cases, invalid data)?

2022-05-02 13:57 UTC, tbruyelle commented on api/chains/chains.go
> +		if StartTime.After(now) && EndTime.Before(now) {
If this condition is never true, you will have a panic here :

https://github.com/EmerisHQ/demeris-api-server/blob/48ec73bd10f78577cf9ae1cf8c48b4130f2a4c69/api/chains/chains.go#L1445

So the question is, are you sure you have at least one `schedule` that meets this requirement?

2022-05-05 05:59 UTC, 0xbala-k commented on api/chains/chains.go
> +		if StartTime.After(now) && EndTime.Before(now) {
initialized `currentInflationAmount` to 0. So, if no schedule is found the APR will be zero.

2022-05-05 06:44 UTC, sgerogia approved these changes

2022-05-05 07:45 UTC, tbruyelle commented on api/chains/chains.go
> +		if StartTime.After(now) && EndTime.Before(now) {
perfect thx

2022-05-05 08:50 UTC, pitasi requested changes

2022-05-05 08:50 UTC, pitasi commented on api/chains/chains.go
> +	budgetParamsResp, err := client.BudgetParams(context.Background(), &sdkutilities.BudgetParamsPayload{
```suggestion
	budgetParamsResp, err := client.BudgetParams(c.Request.Context(), &sdkutilities.BudgetParamsPayload{
```

2022-05-05 08:50 UTC, pitasi commented on api/chains/chains.go
> +	distributionParamsResp, err := client.DistributionParams(context.Background(), &sdkutilities.DistributionParamsPayload{
```suggestion
	distributionParamsResp, err := client.DistributionParams(c.Request.Context(), &sdkutilities.DistributionParamsPayload{
```

2022-05-05 08:50 UTC, pitasi commented on api/chains/chains.go
> +	mintParamsResp, err := client.MintParams(context.Background(), &sdkutilities.MintParamsPayload{
```suggestion
	mintParamsResp, err := client.MintParams(context.Background(), &sdkutilities.MintParamsPayload{
```
```suggestion
	mintParamsResp, err := client.MintParams(c.Request.Context(), &sdkutilities.MintParamsPayload{
```

2022-05-05 11:37 UTC, pitasi approved these changes
lgtm

2022-05-05 11:37 UTC, merged