refactor select * queries
EmerisHQ/demeris-api-server pull request #127
Opened 2022-05-05 06:30 UTC by lukitsbrian

2022-05-05 08:46 UTC, pitasi requested changes
This is great, we'll be much safer when deploying tracelistener.

A couple things:
- can you do that for the other queries too? there are a bunch of others that query `cns` tables
- tests are failing, I suspect those test are creating tables with some missing column because they are not up to date (having "unit" tests that require a real db is not ideal, but for now we'll stick to this 😁 )

Thank you very much!

2022-05-06 12:58 UTC, DeshErBojhaa requested changes

2022-05-06 12:58 UTC, DeshErBojhaa commented on api/database/chains.go
> +			(select chain_name from cns.chains where enabled=TRUE)
All other queries have key words in capital.

2022-05-09 14:30 UTC, pitasi approved these changes

2022-05-09 15:35 UTC, DeshErBojhaa approved these changes

2022-05-09 15:46 UTC, merged