update staking balances calculation and put changes behind feature flag
EmerisHQ/demeris-api-server pull request #135
Opened 2022-05-09 09:09 UTC by akhilkumarpilli

Fixes part of https://github.com/EmerisHQ/demeris-backend/issues/726

2022-05-09 09:57 UTC, pitasi requested changes
I left one comment + I want to say to wait to merge this until Tracelistener is properly deployed and the database schema is properly populated.

As an alternative, we can use a feature flag: [see what I did here](https://github.com/EmerisHQ/demeris-api-server/pull/128). This allow us to merge this PR safely and continue developing without being blocked.

2022-05-09 09:57 UTC, pitasi commented on api/database/delegations.go
> +	AND d.delete_height IS NULL
I know it's unlikely this will happen but to be safe:
```suggestion
	AND d.delete_height IS NULL
	AND v.delete_height IS NULL
```

2022-05-09 13:55 UTC, pitasi commented on api/account/api.go
> +		if !fflag.Enabled(c, chains.RetroCompatStagingDB) {
let's create a new feature flag for this endpoint specifically, we can call it "FixSlashedDelegations" for example. You can define the const in this file :) 

If the flag is enabled -> new behaviour
Else -> old behaviour

2022-05-09 13:56 UTC, pitasi commented on api/database/delegations.go
> +	AND v.delete_height IS NULL
```suggestion
	AND v.delete_height IS NULL
	AND d.delete_height IS NULL
```

2022-05-09 18:17 UTC, tbruyelle commented on api/account/api.go
> +					http.StatusBadRequest,
Database errors should instead be returned as 500.

2022-05-09 18:26 UTC, tbruyelle commented on api/account/api.go
> +				balance := (delegationAmount * validatorTokens) / validatorShares
In the crescent APR calculation PR #123, I noticed we use `math/big` to store the different amounts before the computation, is there a rule stating when we can use  basic types vs `math/big` ?

2022-05-09 18:28 UTC, tbruyelle commented on api/database/delegations.go
> +	WHERE d.delegator_address IN (?)
Why using `IN` when there's always a single address ?

2022-05-10 04:45 UTC, akhilkumarpilli commented on api/account/api.go
> +				balance := (delegationAmount * validatorTokens) / validatorShares
Thanks for this, calculation with basic types will fail if a big value cannot be converted to float64. Will update calculation using sdk types.

2022-05-10 04:45 UTC, akhilkumarpilli commented on api/database/delegations.go
> +	WHERE d.delegator_address IN (?)
Just followed old query. Will update.

2022-05-10 04:47 UTC, akhilkumarpilli commented on api/account/api.go
> +					http.StatusBadRequest,
But this should be 400 as we are fetching delegations based on given input address.

2022-05-10 08:40 UTC, pitasi commented on api/account/api.go
> +					http.StatusBadRequest,
since we don't have API guidelines (yet! we will!) I think any of those is fine. We use 400 in a bunch of other places.
imho we should differentiate between the "you asked for a non-existent address" (404), "address is malformed" (400), and "something went wrong while executing the query" (500). Right now we catch all errors together so... 🤷

2022-05-10 09:04 UTC, pitasi commented on api/database/delegations.go
> +	WHERE delegator_address=(?)
why this change?

2022-05-10 09:39 UTC, akhilkumarpilli commented on api/database/delegations.go
> +	WHERE delegator_address=(?)
As address is always single, we can use `=` instead of `IN`

2022-05-10 09:43 UTC, pitasi commented on api/database/delegations.go
> +	WHERE delegator_address=(?)
uhm ok I see, it should work, but as a rule of thumb I wouldn't modify the old code we know it's working 😛 

anyway, you can leave it like that, it's fine

2022-05-10 09:47 UTC, pitasi approved these changes
lgtm

2022-05-10 19:38 UTC, tbruyelle commented on api/account/api.go
> +					http.StatusBadRequest,
Got it, we'll improve that later

2022-05-10 19:41 UTC, tbruyelle commented on api/account/api.go
> +				balance := (delegationAmount * validatorTokens) / validatorShares
Cool!

2022-05-10 19:41 UTC, tbruyelle commented on api/database/delegations.go
> +	WHERE d.delegator_address IN (?)
OK didn't notice it was already the case in the old query. Thanks for the change.

2022-05-10 19:42 UTC, tbruyelle approved these changes

2022-05-11 06:19 UTC, merged