feat/sentry: add db traces
EmerisHQ/demeris-api-server pull request #143
Opened 2022-05-11 12:41 UTC by tbruyelle

Fix https://github.com/EmerisHQ/demeris-backend/issues/721

Some traces recently added in `api/chains/chains.go` were removed since now they are present in db.

Example:
![image](https://user-images.githubusercontent.com/92280/167852345-bd2b482e-61b3-4bf4-a5ae-d2acf0c462b3.png)

2022-05-12 08:39 UTC, pitasi commented on helm/values.yaml
> +  sentryDSN: https://05d022f3145d43b49fd1aab423ed4ed4@o1152630.ingest.sentry.io/6355661
the dsn appeared again 😁

2022-05-12 08:42 UTC, pitasi requested changes
just left a comment about helm values but lgtm!

2022-05-12 08:44 UTC, tbruyelle commented on helm/values.yaml
> +  sentryDSN: https://05d022f3145d43b49fd1aab423ed4ed4@o1152630.ingest.sentry.io/6355661
Oups again :D ! Thanks to your eyes [0ebdb64](https://github.com/EmerisHQ/demeris-api-server/pull/143/commits/0ebdb645007585d286cc1513bac6dfa3850f6182)

2022-05-12 08:47 UTC, pitasi approved these changes

2022-05-13 06:36 UTC, DeshErBojhaa approved these changes

2022-05-13 09:23 UTC, merged