fix crescent apr
EmerisHQ/demeris-api-server pull request #148
Opened 2022-05-19 09:01 UTC by 0xbala-k

Fix issue due to time format in budget params
This is a temporary fix need to come up with a better way of doing it.

2022-05-19 09:52 UTC, pitasi requested changes

2022-05-19 09:52 UTC, pitasi commented on api/chains/chains.go
> +// to make it ISO-8601 complaint we'll have to change this to "2022-04-13T00:00:00.000Z"
I don't think we need this hack here.

"2022-04-13T00:00:00Z" is ISO-8601 complaint actually. Check this example: https://go.dev/play/p/StDeX3bl25v

2022-05-20 06:47 UTC, 0xbala-k commented on api/chains/chains.go
> +// to make it ISO-8601 complaint we'll have to change this to "2022-04-13T00:00:00.000Z"
Great!! Thanks

2022-05-20 15:50 UTC, pitasi approved these changes

2022-05-23 14:30 UTC, tbruyelle commented on api/chains/chains.go
> +		StartTime, err := time.Parse(time.RFC3339, schedule.StartTime)
@SpideyPool192 @Pitasi Actually if the format is RFC3399, `json.Unmarshal` can properly write it into a `time.Time` (see https://go.dev/play/p/zTt7xk1Uedo)

So instead of 
```go
			StartTime string `json:"start_time"`
			EndTime   string `json:"end_time"`
```
Let's have
```go
			StartTime time.Time `json:"start_time"`
			EndTime   time.Time `json:"end_time"`
```

2022-05-23 15:17 UTC, tbruyelle commented on api/chains/chains.go
> +		StartTime, err := time.Parse(time.RFC3339, schedule.StartTime)
I confirm it's well RFC3399  -> https://mainnet.crescent.network:1317/crescent/mint/v1beta1/params

2022-05-24 13:25 UTC, 0xbala-k commented on api/chains/chains.go
> +		StartTime, err := time.Parse(time.RFC3339, schedule.StartTime)
Even better. 🔥😁
Thanks!!

2022-05-24 13:50 UTC, tbruyelle approved these changes
Nice job!

2022-05-30 06:26 UTC, merged