fixing disabled chains response
EmerisHQ/demeris-api-server pull request #19
Opened 2021-12-21 10:19 UTC by 0xbala-k

Fixes https://github.com/allinbits/demeris-backend/issues/348

2022-01-13 23:01 UTC, sgerogia approved these changes

2022-01-19 16:32 UTC, sahith-narahari commented on api/chains/chains.go
> +	if _, err := d.Database.Chain(chainName); err != nil {
Can we use a different query(something like exists) and return bool. we won't need the chain info anyways

2022-01-20 10:59 UTC, 0xbala-k commented on api/chains/chains.go
> +	if _, err := d.Database.Chain(chainName); err != nil {
This requires adding a `ChainExists` func to the api/database package. Should I go for it?

2022-01-20 18:27 UTC, sahith-narahari commented on api/chains/chains.go
> +	if _, err := d.Database.Chain(chainName); err != nil {
If you think it helps reduce complexity, why not

2022-01-21 11:58 UTC, sahith-narahari requested changes
Could you test these changes either manually or in a test?

2022-01-21 11:58 UTC, sahith-narahari commented on api/chains/chains.go
> +		if err == nil {
```suggestion
		if !exists {
```

2022-01-24 06:16 UTC, 0xbala-k commented on api/chains/chains.go
> +		if err == nil {
This is to add an error in case we have a nil error from `ChainExisits`. We are already checking !exists in the above if statement.
Incase of an error from `ChainExists` it returns false,err and that err is directly passed to the `WriteError` function.

2022-01-27 07:26 UTC, sahith-narahari approved these changes

2022-01-28 06:45 UTC, merged