add correlation ids
EmerisHQ/demeris-api-server pull request #20
Opened 2022-01-03 08:22 UTC by PrathyushaLakkireddy

Fixes https://github.com/allinbits/demeris-backend/issues/346

2022-01-05 16:17 UTC, sgerogia commented
If you have not seen it, @gsora has left a relevant comment [in the issue](https://github.com/allinbits/demeris-backend/issues/346#issuecomment-1003944214).

Please replace the existing generated error id to be the `int_correlation_id`

2022-01-06 05:06 UTC, 0xbala-k commented
> If you have not seen it, @gsora has left a relevant comment [in the issue](https://github.com/allinbits/demeris-backend/issues/346#issuecomment-1003944214).
> 
> Please replace the existing generated error id to be the `int_correlation_id`

Yup! Added that in the `Deps.WriteError` function [here](https://github.com/allinbits/demeris-api-server/blob/1b451c7fdea6e888bd5ccb62b518caf2872b3640/api/router/deps/deps.go#L51).

2022-02-10 21:08 UTC, sgerogia commented
@SpideyPool192 I do not think that [this merge](https://github.com/allinbits/emeris-utils/pull/25) automatically created a release
Can you create a minor release of `emeris-utils` and update the code here?

This needs to be reviewed and merged today if possible

2022-02-10 21:08 UTC, sgerogia requested changes

2022-02-10 21:08 UTC, sgerogia commented on api/router/correlation.go
> +	correlationID := c.Request.Header.Get("X-Correlation-id")
Even though HTTP headers are case-insesitive, it makes sense to use a const for the header name

2022-02-11 11:42 UTC, DeshErBojhaa requested changes
Hi, can you write in short why you're panicking in the router instead of writing the error to log (even to the response maybe).

Also please shortly explain the logic behind the panic in deps.go

2022-02-11 11:42 UTC, DeshErBojhaa commented on api/router/correlation_test.go
> +}
Hi, where it's used?

2022-02-11 11:42 UTC, DeshErBojhaa commented on api/router/correlation_test.go
> +func TestCorrelationIDMiddleWare(t *testing.T) {
Consider t.Parallel()?

2022-02-11 11:42 UTC, DeshErBojhaa commented on api/router/correlation_test.go
> +	id, _ := uuid.NewV4()
Why ignoring the err?

2022-02-11 11:50 UTC, sahith-narahari requested changes

2022-02-11 11:50 UTC, sahith-narahari commented on api/router/correlation_test.go
> +type chainsResponse struct {
unused var

2022-02-11 11:50 UTC, sahith-narahari commented on api/router/correlation_test.go
> +type supportedChain struct {
I don't see usages for this one either, are we using these structs somewhere?

2022-02-11 12:18 UTC, pitasi requested changes

2022-02-11 12:18 UTC, pitasi commented on api/router/router.go
> +	r.l = l
is this safe to do? When multiple API calls arrive aren't them executed concurrently and sharing the same router object?

even it this was safe looks like an anti-pattern to me: request-related stuff should stay inside request's context. What's this r.l used for anyway?

2022-02-14 05:51 UTC, 0xbala-k commented on api/router/correlation_test.go
> +}
Used this earlier. Forgot to remove.

2022-02-14 05:51 UTC, 0xbala-k commented on api/router/correlation_test.go
> +type supportedChain struct {
Used this earlier. Forgot to remove.

2022-02-14 06:01 UTC, 0xbala-k commented
> Hi, can you write in short why you're panicking in the router instead of writing the error to log (even to the response maybe).
> 
> Also please shortly explain the logic behind the panic in deps.go



> Hi, can you write in short why you're panicking in the router instead of writing the error to log (even to the response maybe).
> 
> Also please shortly explain the logic behind the panic in deps.go

The issue suggests that we use a logger from the context if it doesn't exist check if there is another logger (to the router) provided. If there is no logger found we panic.

In deps.go we are trying to replace the error id with the internal correlation id which we created earlier. Hence, we try to find it in the context and panic if not found.

2022-02-14 06:05 UTC, 0xbala-k commented on api/router/router.go
> +	r.l = l
We set a modified logger to the context in the `CorrelationIDMiddleware` function. Intention is to use this logger everywhere. As the api server uses the logger from router, I'm changing the router logger (r.l) to use the logger from context.

2022-02-14 09:39 UTC, DeshErBojhaa approved these changes
LGTM!

2022-02-14 11:24 UTC, gsora approved these changes

2022-02-14 11:31 UTC, pitasi commented on api/router/router.go
> +	r.l = l
> We set a modified logger to the context in the CorrelationIDMiddleware function. Intention is to use this logger everywhere.

that's ok

> As the api server uses the logger from router, I'm changing the router logger (r.l) to use the logger from context.

I don't get why we need a router logger (+ I'm still concerned about concurrency safety)

2022-02-16 05:43 UTC, akhilkumarpilli approved these changes

2022-02-16 08:23 UTC, 0xbala-k commented on api/router/router.go
> +	r.l = l
cc @gsora @sahith-narahari

2022-02-17 05:40 UTC, merged