Add endpoint for destination ibc hash
EmerisHQ/demeris-api-server pull request #34
Opened 2022-01-17 14:09 UTC by sahith-narahari

Closes: https://github.com/allinbits/demeris-backend/issues/258

2022-01-18 09:32 UTC, gsora commented on api/tx/ibc.go
> +	url := fmt.Sprintf("http://%s:26657/tx?hash=%s&prove=%t", srcChain, "0x"+txHash, false)
PSA: we have a method on SDK service which returns JSON bytes from the `GetTx` Cosmos SDK endpoint.

Shall we use that instead of a REST call?

The Cosmos REST API will go away _soon™️_, better be safe than sorry.

2022-01-18 09:33 UTC, gsora commented on api/tx/ibc.go
> +	r := gjson.GetBytes(bz, "result.tx_result.events.3.attributes.3.value")
Please document this/make this string a constant, for future reference.

2022-01-18 13:00 UTC, sahith-narahari commented on api/tx/ibc.go
> +	url := fmt.Sprintf("http://%s:26657/tx?hash=%s&prove=%t", srcChain, "0x"+txHash, false)
Oh didn't know that, replaced

2022-01-20 07:49 UTC, DeshErBojhaa requested changes
Mostly LGTM! Some comments, some concerns.

2022-01-20 07:49 UTC, DeshErBojhaa commented on api/tx/api.go
> +	router.GET("/tx/:srcChain/:destChain/:txHash", GetDestTx)
I would suggest `/tx/:src-chain/:dest-chain/:tx-hash` because it's kinda norm for rest in the industry. But no big issue.

2022-01-20 07:49 UTC, DeshErBojhaa commented on api/tx/ibc.go
> +	txHash := c.Param("txHash")
Iff you decide to change the url, please also change these. `c.Param("src-chain")` and so on.

2022-01-20 07:49 UTC, DeshErBojhaa commented on api/tx/ibc.go
> +	resp, err := http.Get(url) // nolint: gosec
Hi, http.Get uses client with 0 time out. I wonder if it can cause any issue down the path? I know for tests and public url(s) that are 99.99% time available, using http.Get is okay. But I don't know what is the SLA for this URL.

I would suggest 
```go
c := &http.Client{
    Timeout: something,
}
resp, err := c.Get(url)
```

2022-01-20 13:15 UTC, sahith-narahari commented on api/tx/ibc.go
> +	resp, err := http.Get(url) // nolint: gosec
I agree, I created an issue sometime back for the same concern https://github.com/allinbits/demeris-backend/issues/295. This is a request to internal apis(node apis for internal nodes), but it's still better we do this. I'll change it

2022-01-21 08:11 UTC, DeshErBojhaa approved these changes
LGTM

2022-01-21 14:00 UTC, sgerogia approved these changes

2022-01-21 14:00 UTC, sgerogia commented on api/tx/ibc.go
> +	packetSequencePath = "tx_response.logs.0.events.2.attributes.3.value"
Noob q:
Is this per chain, per SDK version or global?

2022-01-21 14:00 UTC, sgerogia commented on api/tx/ibc.go
> +	timeout = 10 * time.Second
Can this be configured externally as an env var via Helm with a default val?
Maybe we could fine-tune in the future w/o needing a code change

Or is it based on the block time, therefore no need to fine-tune?

2022-01-21 14:00 UTC, sgerogia commented on api/tx/ibc.go
> +	url := fmt.Sprintf("http://%s:26657/tx_search?query=\"recv_packet.packet_sequence=%s\"", destChainInfo.ChainName, r.String())
There is an assumption here on the network topology

2022-01-23 17:48 UTC, sahith-narahari commented on api/tx/ibc.go
> +	timeout = 10 * time.Second
This shouldn't change unless the time to process a request changes a lot in our internal setup. Like it should never take longer than 10s to process a rpc request (by one of our chain nodes)

2022-01-23 17:48 UTC, sahith-narahari commented on api/tx/ibc.go
> +	url := fmt.Sprintf("http://%s:26657/tx_search?query=\"recv_packet.packet_sequence=%s\"", destChainInfo.ChainName, r.String())
hmm, true. Do we want to configure this to process it from a single function, maybe in utils?

2022-01-23 17:48 UTC, sahith-narahari commented on api/tx/ibc.go
> +	packetSequencePath = "tx_response.logs.0.events.2.attributes.3.value"
This is per ibc-go version, as mentioned in the note. It might change if sdk changes the entire tx response to something totally different( has been this way for sometime, but doesn't guarantee it won't break)

2022-01-26 11:23 UTC, merged