unverifed chains status
EmerisHQ/demeris-api-server pull request #50
Opened 2022-02-07 08:44 UTC by 0xbala-k

Closes https://github.com/allinbits/demeris-backend/issues/224

2022-02-18 17:40 UTC, 0xbala-k commented
The failing test will pass after https://github.com/allinbits/emeris-utils/pull/35 is merged.

2022-02-23 09:59 UTC, sahith-narahari requested changes

2022-02-23 09:59 UTC, sahith-narahari commented on api/database/errors.go
> +type ErrNoDestChain struct {
Any reason we're renaming this, old one seems more appropriate

2022-02-23 09:59 UTC, sahith-narahari commented on api/database/ibc_channel.go
> +	// q := `
please remove commented code, or add comments why it would be needed

2022-02-23 09:59 UTC, sahith-narahari commented on api/router/correlation_test.go
> +		return count == 4
can you explain why this is changing in this pr

2022-02-23 09:59 UTC, sahith-narahari commented on api/chains/chains.go
> +			cause := fmt.Sprintf("%s : not primary channel for chain %s- expecting %s got %s", hash, chainName, primaryChannelInfo.ChannelName, channel)
please break it into two lines forbetter readability```suggestion
			cause := fmt.Sprintf("%s : not primary channel for chain %s- expecting %s got %s",
				hash, chainName, primaryChannelInfo.ChannelName, channel)
```

2022-02-23 09:59 UTC, sahith-narahari commented on api/chains/migration_test.go
> +func truncateTracelistener(t *testing.T) {
are we testing migrations or is this a test for the updated db query?

2022-02-24 06:59 UTC, 0xbala-k commented on api/chains/migration_test.go
> +func truncateTracelistener(t *testing.T) {
Just to clear all the tables so that we don't get data from previous test case.

2022-02-24 07:01 UTC, sahith-narahari commented on api/chains/migration_test.go
> +func truncateTracelistener(t *testing.T) {
let me rephrase it, what are we testing in this file. If it's db queries, don't we have a base setup to do that?

2022-02-24 07:07 UTC, 0xbala-k commented on api/router/correlation_test.go
> +		return count == 4
It was just a small change depending on the log request PR in utils. So thought do it in this PR instead of creating another.

2022-02-24 07:12 UTC, 0xbala-k commented on api/database/errors.go
> +type ErrNoDestChain struct {
Cause we use this error with `GetIbcChannelToChain` function which tries to find the destination chain info when source chain name,id and channel id is passed.

2022-02-25 06:51 UTC, 0xbala-k commented on api/chains/migration_test.go
> +func truncateTracelistener(t *testing.T) {
Okay, Just moved these migrations to utils. Please have a look.

2022-02-28 14:50 UTC, sgerogia approved these changes

2022-03-02 07:30 UTC, DeshErBojhaa approved these changes
Please addr the comment I left.

2022-03-02 07:30 UTC, DeshErBojhaa commented on api/chains/chains.go
> +					fmt.Errorf("failed querying for %s, error:%w", hash, err),
Space b2in `error:%w` -> `error: %w`?

2022-03-02 11:43 UTC, PrathyushaLakkireddy approved these changes

2022-03-03 04:45 UTC, akhilkumarpilli approved these changes

2022-03-04 07:03 UTC, sahith-narahari approved these changes

2022-03-04 07:07 UTC, merged