feat: add validator avatars
EmerisHQ/demeris-api-server pull request #59
Opened 2022-02-15 17:21 UTC by pitasi

This pr closes https://github.com/allinbits/demeris-backend/issues/447. It introduces a new "avatar" field to responses of `/chain/:name/validators` endpoint.

The avatar is fetched using keybase public api (introducing a new `keybase` pkg containing a small http client for keybase api).

I introduced a small `stringcache` pkg that hold the "caching" logic. I hope the with Go 1.18 we will be able to generalise it to store any kind of data and not only strings.
I used store.Store as (what I called) a "backend" for the cache, so that we may decide to switch to Cockroach or whatever we want in the future.

The policy of the cache is to "cache errors", or better said, to remember even if the handler (keybase) returned an error (i.e. 404). This way we don't hit keybase too much for the validators that don't want to have an avatar there.

2022-02-25 14:53 UTC, sgerogia approved these changes

2022-02-25 14:53 UTC, sgerogia commented on lib/keybase/keybase.go
> +	res, err := httpClient.Do(req)
Apologies if I missed it:
Is there an explicit timeout set somewhere?

If not, can we set one?

2022-02-25 14:53 UTC, sgerogia commented on lib/keybase/keybase.go
> +	res, err := httpClient.Do(req)
Ignore, just saw it a couple of lines down 😶‍🌫️

2022-02-28 14:45 UTC, gsora requested changes

2022-02-28 14:45 UTC, gsora commented on api/chains/models.go
> +	Validators []*Validator `json:"validators"`
Why a slice of pointers here?

2022-02-28 14:45 UTC, gsora commented on api/chains/validators.go
> +		24*time.Hour,
Can you move this to a constant + a comment explaining what it represents?

2022-02-28 14:45 UTC, gsora commented on api/chains/validators.go
> +		"api-server/validator-avatars",
Same here :)

2022-02-28 14:45 UTC, gsora commented on lib/keybase/keybase.go
> +		Path:     "/_/api/1.0/user/lookup.json",
Constant here please!

2022-02-28 14:45 UTC, gsora commented on lib/keybase/keybase.go
> +	dec := json.NewDecoder(res.Body)
Should we check HTTP status code before unmarshaling?

2022-02-28 14:45 UTC, gsora commented on lib/keybase/keybase.go
> +	Status Status
JSON struct tags are missing here.

2022-02-28 14:45 UTC, gsora commented on lib/keybase/keybase.go
> +func UserLookup(c context.Context, query UserLookupQuery, fields []string) (*UserLookupResponse, error) {
Why are you returning a pointer here?

2022-02-28 14:45 UTC, gsora commented on lib/stringcache/storebackend.go
> +func (s *StoreBackend) Get(ctx context.Context, key string) (*string, error) {
Why a `*string` return value?

2022-02-28 14:45 UTC, gsora commented on lib/stringcache/stringcache.go
> +		c.l.Infow(
Maybe let's use `Debugw` here, to reduce chatter during non-debug execution.

2022-02-28 14:45 UTC, gsora commented on lib/stringcache/stringcache.go
> +				"updating cache, proceeding anyway",
What does "proceeding anyway" means here?

2022-02-28 14:48 UTC, pitasi commented on lib/stringcache/stringcache.go
> +				"updating cache, proceeding anyway",
an error occurred while updating the cache, but we still return the result value

2022-02-28 14:59 UTC, pitasi commented on lib/stringcache/storebackend.go
> +func (s *StoreBackend) Get(ctx context.Context, key string) (*string, error) {
i wanted to be able to have three cases
- an error occurred while fetching from cache
- cache was present and that was it's content (string)
- cache was missing

maybe it's more idiomatic to a third bool result value?

2022-02-28 15:17 UTC, gsora commented on lib/stringcache/storebackend.go
> +func (s *StoreBackend) Get(ctx context.Context, key string) (*string, error) {
I would create two errors:
 - `ErrCacheFetch`
 - `ErroCacheMiss`
rather than adding return values/using pointers.

2022-02-28 15:55 UTC, pitasi commented on api/chains/models.go
> +	Validators []*Validator `json:"validators"`
I removed the pointer

2022-02-28 15:55 UTC, pitasi commented on api/chains/validators.go
> +		24*time.Hour,
done :)

2022-02-28 15:55 UTC, pitasi commented on lib/keybase/keybase.go
> +	dec := json.NewDecoder(res.Body)
makes sense, done

2022-02-28 15:55 UTC, pitasi commented on lib/keybase/keybase.go
> +	Status Status
oops, added

2022-02-28 15:57 UTC, pitasi commented on lib/keybase/keybase.go
> +func UserLookup(c context.Context, query UserLookupQuery, fields []string) (*UserLookupResponse, error) {
removed the pointer

2022-02-28 15:57 UTC, pitasi commented on lib/stringcache/storebackend.go
> +func (s *StoreBackend) Get(ctx context.Context, key string) (*string, error) {
makes sense, I added a ErrCacheMiss to the generic "stringcache" struct

other errors in my head will be backend-dependent

2022-02-28 15:58 UTC, pitasi commented on lib/stringcache/stringcache.go
> +		c.l.Infow(
done

2022-03-01 09:29 UTC, pitasi commented
GitHub actions fail but not caused by this PR.

Linter fix: #69 

I'm working on fix the code_cov flakyness too.

2022-03-01 14:30 UTC, gsora commented on lib/stringcache/stringcache.go
> +				"updating cache, proceeding anyway",
Maybe a warning is more appropriate then

2022-03-01 14:30 UTC, gsora approved these changes

2022-03-01 14:42 UTC, pitasi commented on lib/stringcache/stringcache.go
> +				"updating cache, proceeding anyway",
hmm but something is going on, i.e. connection to Redis failed

2022-03-01 15:07 UTC, merged