Remove Primary channel check from verify_trace
EmerisHQ/demeris-api-server pull request #71
Opened 2022-03-02 11:02 UTC by 0xbala-k

Closes https://github.com/allinbits/demeris-backend/issues/511

2022-03-04 12:31 UTC, pitasi requested changes
i think some tests needs to be fixed (currently failing in CI)

2022-03-08 06:01 UTC, 0xbala-k commented
> i think some tests needs to be fixed (currently failing in CI)

That's weird!!
It passes on my local env.

2022-03-08 07:49 UTC, pitasi commented
Yeah sorry, I believe the problem was another, it should be fixed by the last pr I merged. Hopefully everything works now 😁

2022-03-10 08:04 UTC, pitasi approved these changes

2022-03-10 09:29 UTC, sgerogia approved these changes

2022-03-10 10:22 UTC, merged