Staking APR endpoint
EmerisHQ/demeris-api-server pull request #84
Opened 2022-03-28 06:25 UTC by 0xbala-k

Closes https://github.com/EmerisHQ/demeris-backend/issues/606

2022-03-31 06:41 UTC, PrathyushaLakkireddy approved these changes

2022-03-31 07:37 UTC, pitasi commented on api/chains/chains.go
> -	_ "encoding/json"
uhm is it ok to remove this line? it says "needed for swagger gen" 😬

2022-03-31 08:06 UTC, pitasi commented on api/chains/chains.go
> +	}
can this be a chance to use `stringcache` pkg? see https://github.com/EmerisHQ/demeris-api-server/blob/main/api/chains/validators.go#L57-L63 basically it takes the key + a function to revalidate the cache

2022-03-31 08:12 UTC, pitasi commented on api/chains/api.go
> +		GET("/APR", GetStakingAPR).
```suggestion
		GET("/apr", GetStakingAPR).
```

I would keep all paths/urls lowercase as a convention

2022-03-31 08:25 UTC, pitasi commented on api/chains/models.go
> +	}
is it correct that it's missing the json tag here?

```suggestion
	} `json:"params"`
```

2022-03-31 08:25 UTC, pitasi commented on api/chains/models.go
> +	}
is it correct that it's missing the json tag here?

```suggestion
	} `json:"pool"`
```

2022-03-31 09:55 UTC, 0xbala-k commented on api/chains/chains.go
> -	_ "encoding/json"
Using the package to unmarshal anyhow. I'll just remove the comment.

2022-03-31 10:00 UTC, pitasi commented on api/chains/chains.go
> -	_ "encoding/json"
ah! I missed it was moved some lines above

2022-03-31 10:13 UTC, 0xbala-k commented on api/chains/chains.go
> +	}
this requires that we move apr calculation logic to the middleware func right? But the current parameters to the [handler func](https://github.com/EmerisHQ/demeris-api-server/blob/985684e7dc326cfbf9285f422f49ab3c4b5888d2/lib/stringcache/stringcache.go#L34) won't be enough. We will need to send gin context too.

2022-03-31 10:20 UTC, pitasi commented on api/chains/chains.go
> +	}
no there's no need for middlewares

you can initialize a new cache:
```go
	aprCache := stringcache.NewStringCache(
		d.Logger,
		stringcache.NewStoreBackend(d.Store),
		aprCacheDuration,
		aprCachePrefix,
		stringcache.HandlerFunc(getAPR(d)),
	)
```

then you use the cache like that

```go
	apr, err = cache.Get(ctx, chain.ChainName)
    // return apr as a result
```

and finally the real work is to define this:

```go
func getAPR(d *deps.Deps) {
  return func(ctx context.Context, key string) (string, error) {
    // rest of the code you now have inside the handler
  }
}
```

2022-03-31 10:21 UTC, pitasi commented on api/chains/chains.go
> +	}
the real problem I see is that my cache was only a "string" cache while now it could be generalized to store any kind of data. Right now you would get a string apr when calling `cache.Get()` while you actually wanted a float I believe :/

2022-03-31 11:17 UTC, 0xbala-k commented on api/chains/chains.go
> +	}
for now im just converting. Maybe we can address this in a different PR for this to be type independent.

2022-03-31 12:03 UTC, pitasi commented on api/chains/chains.go
> +			return "", err
inside this `getAPR` function you can just return regular errors (like normal go functions) and then eventually they will be sent back to the client after the `aprCache.Get()` call (lines 1223-1240)

2022-03-31 12:36 UTC, 0xbala-k commented on api/chains/chains.go
> +			return "", err
But we will also have to create `deps.NewError` referring to the origin of the error. Is there a way to add that to the error?

2022-03-31 13:36 UTC, DeshErBojhaa approved these changes
LGTM!!

2022-03-31 13:58 UTC, pitasi commented on api/chains/chains.go
> +			return "", err
you could return just the message like `return "", fmt.Errorf("cannot retrieve chain's sdk-service for version %s with chain name %v")`

or can return the entire Error:
```
return "", deps.NewError(...)
```

but in that second case you will lose the user message ("cannot retrieve chain's sdk-service"), uhm we will need a refactor of those errors for managing them in a an easier way

2022-03-31 13:59 UTC, pitasi commented on api/chains/chains.go
> +			return "", err
right now you are basically writing the error twice (d.WriteError is called both here and inside the handler), but I think that's okay, the middleware will just return both the errors without problems

we can think of a refactor later

2022-03-31 18:28 UTC, lukitsbrian requested changes

2022-03-31 18:28 UTC, lukitsbrian commented on api/chains/chains.go
> +func getAPR(c *gin.Context) stringcache.HandlerFunc {
please also include edge case chains with their own mint modules, eg. osmosis and iris

2022-03-31 18:49 UTC, lukitsbrian commented on api/chains/chains.go
> +func getAPR(c *gin.Context) stringcache.HandlerFunc {
and emoney

2022-04-01 07:18 UTC, 0xbala-k commented on api/chains/chains.go
> +func getAPR(c *gin.Context) stringcache.HandlerFunc {
These exceptions have already been considered in mintInflation func so we can directly use that to get inflation.
But inflation for osmosis wasn't included in that, which will be addressed in a new issue.

2022-04-01 07:20 UTC, 0xbala-k commented on api/chains/chains.go
> +func getAPR(c *gin.Context) stringcache.HandlerFunc {
https://staging.demeris.io/v1/chain/emoney/mint/inflation
https://dev.demeris.io/v1/chain/iris/mint/inflation

2022-04-02 14:56 UTC, merged