Add mergify config
EmerisHQ/demeris-api-server pull request #86
Opened 2022-03-29 06:12 UTC by akhilkumarpilli

Fixes part of issue: https://github.com/EmerisHQ/demeris-backend/pull/641

2022-03-30 07:36 UTC, pitasi requested changes

2022-03-30 07:36 UTC, pitasi commented on .mergify.yml
> +      - check-success=build
```suggestion
      - check-success=build
      - check-success=code_cov
```

2022-03-30 08:21 UTC, pitasi approved these changes

2022-03-31 05:51 UTC, PrathyushaLakkireddy approved these changes

2022-03-31 06:38 UTC, merged