#227 Add unit tests
EmerisHQ/demeris-api-server pull request #9
Opened 2021-12-01 22:20 UTC by sgerogia

2021-12-02 10:15 UTC, DeshErBojhaa requested changes
Almost there!

2021-12-02 10:15 UTC, DeshErBojhaa commented on api/chains/chains_test.go
> +			require.NoError(t, err)
nit picking, but order of these 3 lines should be,
```go
resp, err := http.Get(fmt.Sprintf(chainEndpointUrl, testingCtx.Cfg.ListenAddr, tt.chainName))
require.NoError(t, err)
defer func() { _ = resp.Body.Close() }()
````
Same for other tests.

2021-12-02 10:15 UTC, DeshErBojhaa commented on api/chains/chains_test.go
> +package chains_test
👏🏼 for external test.

2021-12-02 10:15 UTC, DeshErBojhaa commented on api/test_utils/utils.go
> +	assert.NoError(t, err)
Question: since we're using `require` almost everywhere, I wonder why we're using assert here?

2021-12-02 14:56 UTC, sgerogia commented on api/test_utils/utils.go
> +	assert.NoError(t, err)
My bad, maybe copy-paste. Replaced.

2021-12-14 09:42 UTC, DeshErBojhaa approved these changes
LGTM! With one comment!

2021-12-14 09:42 UTC, DeshErBojhaa commented on api/chains/chains_test.go
> +			}
One suggestion, some people like it some don't, your call if you consider it or not.
```go
if !tt.success {
    require.Equal(t, tt.expectedHttpCode, resp.StatusCode)
    continue
}

body, err := ioutil.ReadAll(resp.Body)
require.NoError(t, err)

respStruct := chains.ChainResponse{}
err = json.Unmarshal(body, &respStruct)
require.NoError(t, err)

require.Equal(t, tt.expectedHttpCode, resp.StatusCode)
require.Equal(t, tt.dataStruct, respStruct.Chain)

```
Keeps nesting 1 level less.
However, if you opt for this approach, please change all the following occurrences.

2021-12-16 06:17 UTC, sahith-narahari requested changes

2021-12-16 06:17 UTC, sahith-narahari commented on api/chains/chains_test.go
> +			}
I agree, this is more readable and better to avoid nesting

2022-01-18 13:40 UTC, sgerogia commented on api/chains/chains_test.go
> +			}
Fixed with `return`, as inside a method rather than a loop

2022-01-18 14:46 UTC, sahith-narahari approved these changes

2022-01-18 14:51 UTC, merged